version: 0.2

env:
  shell: bash
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - pip3 install awscli --upgrade --user
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - aws secretsmanager get-secret-value --secret-id $SECRETS_MANAGER_SECRET_ID --region $AWS_REGION | jq -r '.SecretString' | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" | tee .env
      - docker run -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI --env-file .env -v $(pwd)/build:/app/build $ECR_IMAGE_URI # Run the build script inside the container

artifacts:
  files:
    - '**/*'
  base-directory: build # The build directory is where the container outputs the static files
