version: 0.2

env:
  shell: bash
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - docker run -e AWS_REGION=$AWS_REGION -e SECRETS_MANAGER_SECRET_ID=$SECRETS_MANAGER_SECRET_ID -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI -v $(pwd)/build:/app/build $ECR_IMAGE_URI # Run the build script inside the container

artifacts:
  files:
    - '**/*'
  base-directory: build # The build directory is where the container outputs the static files
