version: 0.2

env:
  shell: bash
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECS_CONTAINER_NAME $ECR_IMAGE_URI > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
